export const POST_CATEGORIES = [
  { value: 'frontend-development', label: 'Frontend Development' },
  { value: 'frontend-frameworks', label: 'Frontend Frameworks' },
  { value: 'backend-development', label: 'Backend Development' },
  { value: 'databases', label: 'Databases' },
  { value: 'full-stack-development', label: 'Full Stack Development' },
  { value: 'blockchain-fundamentals', label: 'Blockchain Fundamentals' },
  { value: 'ethereum-ecosystem', label: 'Ethereum Ecosystem' },
  { value: 'solana-ecosystem', label: 'Solana Ecosystem' },
  { value: 'ton-blockchain', label: 'TON Blockchain' },
  { value: 'enterprise-blockchain', label: 'Enterprise Blockchain' },
  { value: 'defi-refi', label: 'DeFi & ReFi' },
  { value: 'data-structures-algorithms', label: 'Data Structures & Algorithms' },
  { value: 'artificial-intelligence', label: 'Artificial Intelligence' },
  { value: 'machine-learning', label: 'Machine Learning' },
  { value: 'deep-learning', label: 'Deep Learning' },
  { value: 'cyber-security', label: 'Cyber Security' },
  { value: 'android-development', label: 'Android Development' },
  { value: 'ios-development', label: 'iOS Development' },
  { value: 'cross-platform', label: 'Cross Platform' },
  { value: 'cloud-devops', label: 'Cloud & DevOps' },
  { value: 'programming-languages', label: 'Programming Languages' },
  { value: 'computer-science-core', label: 'Computer Science Core' },
  { value: 'competitive-programming', label: 'Competitive Programming' },
  { value: 'career-interview-prep', label: 'Career & Interview Prep' },
  { value: 'projects-case-studies', label: 'Projects & Case Studies' },
  { value: 'emerging-technologies', label: 'Emerging Technologies' },
  { value: 'mathematics-for-cs', label: 'Mathematics for CS' },
  { value: 'student-growth', label: 'Student Growth' }
];
